name: Test Parser

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: "24"
                  cache: "npm"

            - name: Setup PHP 8.2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"

            - name: Install dependencies
              run: npm install

            - name: Compile
              run: npm run compile

            - name: Run parser tests
              run: npx mocha ./out/test/**/*.test.js -u tdd --slow 10000 --timeout 20000 --parallel --colors --dot --reporter dot --colors
